CREATE SCHEMA IF NOT EXISTS `admin`;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT,
    login VARCHAR(35) NOT NULL,
    password VARCHAR(35) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS notes (
    id INT AUTO_INCREMENT,
    login VARCHAR(20) NOT NULL,
    password VARCHAR(1000) NOT NULL,
    PRIMARY KEY (id)
);
